### ISSUE TITLE
Python 3: pip install problem

### ISSUE THREAD

**Issue by fisher2099** [quickfix/quickfix#190]
$pip3 install quickfix
Collecting quickfix
  Using cached quickfix-1.14.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6e3pmpnf/quickfix/setup.py", line 14
        print "Testing for std::tr1::shared_ptr..."
                                                  ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Testing for std::tr1::shared_ptr...")?

**Comment by orenmnero** [comment]
Can you try a pip install of the latest (1.15.1) and see if you still have this problem?

**Comment by shapiroyaacov** [comment]
Did just that and it installs great (Ubuntu 16.04).

(Now having another issue with application_2.py:17 :
`AttributeError: module 'quickfix' has no attribute 'MyApplication'`

**Comment by jatin759** [comment]
@shapiroyaacov I am getting the same issue. Were you able to resolve this?

**Comment by orenmnero** [comment]
Duplicate of #198 — same pip/build failure on Windows. The specific version involved (1.14.3) is also quite old. Tracking the broader issue in #198 and #607.
