### ISSUE TITLE
Python3 bytes/string issue -> SWIG_PYTHON_STRICT_BYTE_CHAR

### ISSUE THREAD

**Issue by karulis** [quickfix/quickfix#196]
I have following issue:

```python
import quickfix as fix
import quickfix42 as fix42

trade = fix42.TestRequest()
trade.setField(fix.RawData(b"data"))
```
When run with python3 that results in:
```python
Traceback (most recent call last):
  File "fix_unicode.py", line 6, in <module>
    trade.setField(fix.RawData(b"data"))
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 40179, in __init__
    quickfix.StringField.__init__(self, 96, data)
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 910, in __init__
    this = _quickfix.new_StringField(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_StringField'.
  Possible C/C++ prototypes are:
    FIX::StringField::StringField(int,std::string const &)
    FIX::StringField::StringField(int)

```

This is due to python3 different handling of bytes and strings
Here https://github.com/swig/swig/issues/752 I have found information that
SWIG_PYTHON_STRICT_BYTE_CHAR needs to be definded(as described here http://www.swig.org/Doc3.0/Python.html#Python_nn77)
According to documentation SWIG_PYTHON_STRICT_BYTE_CHAR has no efect for python2

I am not sure where to put this flag, but I am happy to test it on my setup

**Comment by orenmnero** [comment]
I think the real issue is that quickfix is using a string to store this data, will need to pick a better data structure

**Comment by orenmnero** [comment]
This did not work unfortunately. A whole bunch of other tests started failing.

**Comment by orenmnero** [comment]
Branch in case anyone wants to take a look

https://github.com/quickfix/quickfix/compare/master...python_byte_string_support
