### ISSUE TITLE
quickfix调用libssl.so.10遇到空指针，导致程序crash

### ISSUE THREAD

**Issue by exist2013** [quickfix/quickfix#293]
系统环境：centos7 (Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
gcc: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
openssl版本：OpenSSL 1.0.2k-fips  26 Jan 2017
段错误如下：其中cert为NULL指针，导致程序crash
麻烦问下你们有碰到过吗？谢谢

Program terminated with signal 11, Segmentation fault.
#0  ssl3_ctx_ctrl (ctx=0x7fa02f03b800, cmd=<optimized out>, larg=<optimized out>, parg=<optimized out>) at s3_lib.c:3800
3800	            if (cert->ecdh_tmp != NULL) {
(gdb) bt
#0  ssl3_ctx_ctrl (ctx=0x7fa02f03b800, cmd=<optimized out>, larg=<optimized out>, parg=<optimized out>) at s3_lib.c:3800
#1  0x00007fa0343f2358 in FIX::enable_DH_ECDH (ctx=ctx@entry=0x7fa02f03b800, certFile=<optimized out>) at UtilitySSL.cpp:1153
#2  0x00007fa0343f2bb7 in FIX::loadSSLCert (ctx=0x7fa02f03b800, server=server@entry=false, settings=..., log=0x7fa02f060040, cb=cb@entry=0x7fa0343e3160 <FIX::ThreadedSSLSocketInitiator::passwordHandleCB(char*, int, int, void*)>, errStr="") at UtilitySSL.cpp:1388
#3  0x00007fa0343e254c in FIX::ThreadedSSLSocketInitiator::onInitialize (this=0x7fa02f08c600, s=...) at ThreadedSSLSocketInitiator.cpp:213
#4  0x00007fa03436085e in FIX::Initiator::start (this=0x7fa02f08c600) at Initiator.cpp:194
#5  0x000000000044199c in FIXChannel::Init (this=0x7fa02f08f140) at /home/david/code/TradeService/trunk/TradeService/TradeChannel/./FIXChannel.cpp:49

**Comment by exist2013** [comment]
ldd libquickfix.so
	linux-vdso.so.1 =>  (0x00007fffd1d50000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fce9c9d4000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007fce9c761000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fce9c2fe000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fce9bff7000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fce9bcf4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fce9b933000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fce9b71d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fce9cf51000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fce9b4cf000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fce9b1e6000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fce9afe2000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fce9adae000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fce9abaa000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fce9a994000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fce9a783000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fce9a57f000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fce9a365000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fce9a13d000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fce99edb000)

**Comment by exist2013** [comment]
anybody knows?

**Comment by exist2013** [comment]
I solve the problem
