### ISSUE TITLE
pure virtual method called - terminate called without an active exception - core file created

### ISSUE THREAD

**Issue by cid8819** [quickfix/quickfix#294]
I had build the quickfix library with a custom FIX50SP2.xml data dictionary for python3.  When I run my python script everything works fine until at some point it fails with a SIGABRT - pure virtual method called
terminate called without an active exception

I would appreciate if someone could help identify why this error appears.

A core file was created for this error:

gdb output of core:
```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/user1/git/quickfix_project/.worktrees/python3_migration/venv/bin/python3...done.

warning: core file may not match specified executable file.
[New LWP 30501]
[New LWP 30499]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/user1/git/quickfix_project/.worktrees/python3_migration/venv/bin/'.
Program terminated with signal 6, Aborted.
#0  0x00002ac8e65771d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7.x86_64 krb5-libs-1.14.1-26.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 libuuid-2.23.2-33.el7.x86_64 openssl-libs-1.0.1e-60.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64

(gdb) bt
#0  0x00002ac8e65771d7 in raise () from /lib64/libc.so.6
#1  0x00002ac8e65788c8 in abort () from /lib64/libc.so.6
#2  0x00002ac8ed789ab5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00002ac8ed787a26 in ?? () from /lib64/libstdc++.so.6
#4  0x00002ac8ed787a53 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00002ac8ed7885bf in __cxa_pure_virtual () from /lib64/libstdc++.so.6
#6  0x00002ac8ed4bc01b in FIX::SocketMonitor::processReadSet (this=this@entry=0x1d71130, strategy=..., readSet=...) at SocketMonitor.cpp:260
#7  0x00002ac8ed4bc4ba in FIX::SocketMonitor::block (this=this@entry=0x1d71130, strategy=..., poll=poll@entry=false, timeout=timeout@entry=1) at SocketMonitor.cpp:219
#8  0x00002ac8ed4b5bc3 in FIX::SocketConnector::block (this=this@entry=0x1d71130, strategy=..., poll=poll@entry=false, timeout=timeout@entry=1) at SocketConnector.cpp:117
#9  0x00002ac8ed4ba305 in FIX::SocketInitiator::onStart (this=0x1d70e70) at SocketInitiator.cpp:92
#10 0x00002ac8ed4b731d in FIX::Initiator::startThread (p=<optimized out>) at Initiator.cpp:292
#11 0x00002ac8e5c24dc5 in start_thread () from /lib64/libpthread.so.0
#12 0x00002ac8e663973d in clone () from /lib64/libc.so.6

(gdb) bt full
#0  0x00002ac8e65771d7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00002ac8e65788c8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00002ac8ed789ab5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
No symbol table info available.
#3  0x00002ac8ed787a26 in ?? () from /lib64/libstdc++.so.6
No symbol table info available.
#4  0x00002ac8ed787a53 in std::terminate() () from /lib64/libstdc++.so.6
No symbol table info available.
#5  0x00002ac8ed7885bf in __cxa_pure_virtual () from /lib64/libstdc++.so.6
No symbol table info available.
#6  0x00002ac8ed4bc01b in FIX::SocketMonitor::processReadSet (this=this@entry=0x1d71130, strategy=..., readSet=...) at SocketMonitor.cpp:260
        s = <optimized out>
        i = 15
        sockets = std::set with 2 elements = {[0] = 14, [1] = 15}
#7  0x00002ac8ed4bc4ba in FIX::SocketMonitor::block (this=this@entry=0x1d71130, strategy=..., poll=poll@entry=false, timeout=timeout@entry=1) at SocketMonitor.cpp:219
        readSet = {fds_bits = {32768, 0 <repeats 15 times>}}
        writeSet = {fds_bits = {0 <repeats 16 times>}}
        exceptSet = {fds_bits = {0 <repeats 16 times>}}
        result = <optimized out>
#8  0x00002ac8ed4b5bc3 in FIX::SocketConnector::block (this=this@entry=0x1d71130, strategy=..., poll=poll@entry=false, timeout=timeout@entry=1) at SocketConnector.cpp:117
        wrapper = {<FIX::SocketMonitor::Strategy> = {_vptr.Strategy = 0x2ac8ed724270 <vtable for FIX::ConnectorWrapper+16>}, m_connector = @0x1d71130, m_strategy = @0x1d71080}
#9  0x00002ac8ed4ba305 in FIX::SocketInitiator::onStart (this=0x1d70e70) at SocketInitiator.cpp:92
        start = 47042605442816
        now = 24
#10 0x00002ac8ed4b731d in FIX::Initiator::startThread (p=<optimized out>) at Initiator.cpp:292
        pInitiator = <optimized out>
#11 0x00002ac8e5c24dc5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#12 0x00002ac8e663973d in clone () from /lib64/libc.so.6
No symbol table info available.
```

**Comment by leleftheriades** [comment]
I am curious as to why i =15, when there are only 2 sockets and only 1 socket in the readset

**Comment by cid8819** [comment]
Found the issue. There was a bug in my code. I never tried to stop the initiator properly. Somehow this was never an issue with python2 but with python3.
