### ISSUE TITLE
Dll load failed in import quick into my python applicaiton

### ISSUE THREAD

**Issue by helldragonx** [quickfix/quickfix#338]
Platform: Window10
Language: Python 3.6.5
Error Code: import quickfix
Intallation: By pip install the .wl from the web

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\quickfix.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

**Comment by orenmnero** [comment]
We don't produce the wheel, would need to talk to whoever created it.
