### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wldcordeiro** [quickfix/quickfix#54]
It's not very clear from the website or documentation whether Python 3 is supported. Could you provide additional info? Also if it isn't I am willing to assist in adding support and would like details.

**Comment by christhomas** [comment]
I just tried to pip install quickfix from a virtualenv with python3 and it fails

	pip install quickfix
	Downloading/unpacking quickfix
	  Running setup.py egg_info for package quickfix
		Traceback (most recent call last):
		  File "<string>", line 14, in <module>
		  File "/home/somebody/sites/fix.somebodyconsulting.com/build/quickfix/setup.py", line 14
			print "Testing for std::tr1::shared_ptr..."
													  ^
		SyntaxError: invalid syntax
		Complete output from command python setup.py egg_info:
		Traceback (most recent call last):

	  File "<string>", line 14, in <module>

	  File "/home/somebody/sites/fix.somebodyconsulting.com/build/quickfix/setup.py", line 14

		print "Testing for std::tr1::shared_ptr..."

												  ^

	SyntaxError: invalid syntax

	----------------------------------------
	Command python setup.py egg_info failed with error code 1

**Comment by christhomas** [comment]
open the setup.py file is complains about and if on line 14 you'll see 

    print "Testing for std::tr1::shared_ptr..."

this needs to change to

    print("Testing for std::tr1::shared_ptr...")

and then change all the definitions in the same file that you see using the print word, this is because print in python3 is a function, so has to be called this way.

after you make this change, the code starts to compile and seems to be going without a problem so far.

**Comment by christhomas** [comment]
and to finish, it appears to be installed just fine

	(fix.userconsulting.com)user@localhost:~/sites/fix.userconsulting.com$ ls lib/python3.2/site-packages/ -l | grep "quickfix"
	drwxr-xr-x  2 user user     4096 Jan  5 12:08 quickfix-1.14.3-py3.2.egg-info
	-rw-r--r--  1 user user     4825 Jan  5 11:58 quickfix40.py
	-rw-r--r--  1 user user     6232 Jan  5 11:58 quickfix41.py
	-rw-r--r--  1 user user    21580 Jan  5 11:58 quickfix42.py
	-rw-r--r--  1 user user    64741 Jan  5 11:58 quickfix43.py
	-rw-r--r--  1 user user   200399 Jan  5 11:58 quickfix44.py
	-rw-r--r--  1 user user   252341 Jan  5 11:58 quickfix50.py
	-rw-r--r--  1 user user   295553 Jan  5 11:58 quickfix50sp1.py
	-rw-r--r--  1 user user   324097 Jan  5 11:58 quickfix50sp2.py
	-rwxr-xr-x  1 user user 44875025 Jan  5 12:08 _quickfix.cpython-32mu.so
	-rw-r--r--  1 user user  1949041 Jan  5 11:58 quickfix.py
	-rw-r--r--  1 user user     1223 Jan  5 11:58 quickfixt11.py
	(fix.userconsulting.com)user@localhost:~/sites/fix.userconsulting.com$

However, maybe it doesn't run, just compiles :)

**Comment by wldcordeiro** [comment]
@christhomas I can't seem to find the setup.py file in the repo, do you think it's generated?

**Comment by orenmnero** [comment]
There is a separate repository for packaging quickfix.  setup.py can be found there.

https://github.com/quickfix/quickfix-package/blob/master/quickfix-python/setup.py

**Comment by wldcordeiro** [comment]
@orenmnero Cool, I submit a PR to that repo with changes. I'm working on some changes to the Python src here and I was curious if you had any kind of organizational grouping of the fields in quickfix_fields.py file. I was going to try to take that file and move it into a directory with files for each type of field and an `__init__.py` file that exposed all the fields to the module.

**Comment by wldcordeiro** [comment]
Never mind, I saw that it was a generated file and figured out what I needed to do to it.

**Comment by wldcordeiro** [comment]
So I've got it configuring and building for Python 3 but I'm getting an issue importing the quickfix library in Python. This is the traceback that I get. Could you point me towards the files that generate this?
```py
>>> from quickfix import quickfix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/quickfix.py", line 28, in <module>
    _quickfix = swig_import_helper()
  File "/usr/lib/python3/dist-packages/quickfix.py", line 24, in swig_import_helper
    _mod = imp.load_module('_quickfix', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: libquickfix.so.16: cannot open shared object file: No such file or directory
```

**Comment by wldcordeiro** [comment]
I'm going to continue updating with progress here.

So the issue above was fixed. I just used the quickfix-package repo to generate a tar and installed from there. Now I'm trying to run the Python test suites and two aren't passing with specific errors.

First `DataDictionaryTestCase.py`, this one is throwing the following error.
```sh
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
[1]    18628 abort (core dumped)  python3 DataDictionaryTestCase.py
```
from looking online it appears that this means that some kind of std::string is being set to null.

Next there's `MessageTestCase.py` which fails two tests with these errors
```py
MessageTestCase.py:13: DeprecationWarning: Please use assertTrue instead.
  self.failUnless(self.object.isAdmin() == 0)
...MessageTestCase.py:153: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(expected, self.object.toString())
....EE
======================================================================
ERROR: test_setStringWithGroup (__main__.MessageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "MessageTestCase.py", line 128, in test_setStringWithGroup
    dataDictionary = fix.DataDictionary("spec/FIX43.xml")
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 31106, in __init__
    this = _quickfix.new_DataDictionary(*args)
quickfix.ConfigError: Configuration failed: spec/FIX43.xml: Could not parse data dictionary file

======================================================================
ERROR: test_setStringWithHeaderGroup (__main__.MessageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "MessageTestCase.py", line 138, in test_setStringWithHeaderGroup
    dataDictionary = fix.DataDictionary("spec/FIX43.xml")
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 31106, in __init__
    this = _quickfix.new_DataDictionary(*args)
quickfix.ConfigError: Configuration failed: spec/FIX43.xml: Could not parse data dictionary file

----------------------------------------------------------------------
Ran 9 tests in 0.006s

FAILED (errors=2)
```

Now I modified `quickfix/spec/FIX43.xml` line 3954 because of issue #52 from
```xml
<field number='536' name='AffectedSecondaryOrderID' type='STIRNG' />
```
to
```xml
<field number='536' name='AffectedSecondaryOrderID' type='STRING' />
```

which could have been the cause of the `MessageTestCase.py` errors.

Thanks for the great library @orenmnero I'm going to continue working on Python 3 support.

**Comment by wldcordeiro** [comment]
I fixed the issues in the MessageTestCase.py file. Now in the DataDictionaryTestCase.py I'm getting this error for the following assertions.
`terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid`

```py
self.assertEqual("Account", self.object.getFieldName(1, "")[0])
self.assertEqual("ClOrdID", self.object.getFieldName(11, "")[0])
self.assertEqual("BeginString", self.object.getFieldName(8, "")[0])
self.assertEquals("VALUE_12_0", self.object.getValueName(12, "0", "")[0])
self.assertEquals("VALUE_12_B", self.object.getValueName(12, "B", "")[0])
self.assertEquals("VALUE_23_BOO", self.object.getValueName(23, "BOO", "")[0])
```

Looking at the definition of getFieldName, it's supposed to return True or False
```c++
  bool getFieldName( int field, std::string& name ) const
  {
    FieldToName::const_iterator i = m_fieldNames.find( field );
    if(i == m_fieldNames.end()) return false;
    name = i->second;
    return true;
  }
```
 so I'm not certain what these assertions are trying to do.

**Comment by andradei** [comment]
@orenmnero 
I got the same conclusion, but the error I'm getting is different running on an OS X 10.10 system:
```shell
python3 test/DataDictionaryTestCase.py
[1]    66212 segmentation fault  python3 test/DataDictionaryTestCase.py
```

And right after my Python Interpreter crashes:

![screen shot 2015-02-10 at 16 07 21](https://cloud.githubusercontent.com/assets/2653546/6138509/f4b57d52-b13e-11e4-9c27-3fb6e6eed4d8.png)

This seems to be due to the fact that [Python strings are immutable](http://www.swig.org/Doc1.3/Python.html#Python_nn49):

>When a Python string is passed as a parameter, the C function receives a pointer to the raw data contained in the string. Since Python strings are immutable, it is illegal for your program to change the value. In fact, doing so will probably crash the Python interpreter. 

The link above explains the exact behavior I'm getting on my system, and I believe _lines 113 and 134 of_ `DataDictionary.h` (one of which methods where quoted by @wldcordeiro above) causes the crash with Python code.

**Comment by wldcordeiro** [comment]
PR #60 is the current work in progress of my attempt to add Python 3 support.

I've been able to fix the issue with the null std::string constructor but now this is the error that's occurring.

```
./test3.sh                                                                                                                                 master 
E.E.....E....
======================================================================
ERROR: test_addFieldName (__main__.DataDictionaryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/DataDictionaryTestCase.py", line 114, in test_addFieldName
    self.assertEqual("Account", self.object.getFieldName(1, "")[0])
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 39772, in getFieldName
    return _quickfix.DataDictionary_getFieldName(self, field, name)
TypeError: in method 'DataDictionary_getFieldName', argument 3 of type 'std::string &'

======================================================================
ERROR: test_addGroup (__main__.DataDictionaryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/DataDictionaryTestCase.py", line 95, in test_addGroup
    result = self.object.getGroup("A", 100, delim, d)
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 39838, in getGroup
    return _quickfix.DataDictionary_getGroup(self, msg, field, delim, pDataDictionary)
TypeError: in method 'DataDictionary_getGroup', argument 4 of type 'int &'

======================================================================
ERROR: test_addValueName (__main__.DataDictionaryTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/DataDictionaryTestCase.py", line 129, in test_addValueName
    "VALUE_12_0", self.object.getValueName(12, "0", "")[0])
  File "/usr/local/lib/python3.4/dist-packages/quickfix.py", line 39781, in getValueName
    return _quickfix.DataDictionary_getValueName(self, field, value, name)
TypeError: in method 'DataDictionary_getValueName', argument 4 of type 'std::string &'

----------------------------------------------------------------------
Ran 13 tests in 0.007s

FAILED (errors=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.........
----------------------------------------------------------------------
Ran 9 tests in 0.018s

OK
```

The quickfix.i file now looks like this
```cpp
%include ../quickfix.i

#ifdef SWIGPYTHON
%typemap(in) std::string& (std::string temp) {
  temp = std::string((char*)PyUnicode_AsUTF8($input));
  $1 = &temp;
}    
       
%typemap(argout) std::string& {
  if( std::string("$1_type") == "std::string &" )
  {
    if( !PyDict_Check(resultobj) )
      resultobj = PyDict_New();
    PyDict_SetItem( resultobj, PyLong_FromLong(PyDict_Size(resultobj)), PyUnicode_FromString($1->c_str()) );
  }
}

%typemap(in) int& (int temp) {
  SWIG_AsVal_int($input, &temp);
  $1 = &temp;
}

%typemap(argout) int& {
  if( std::string("$1_type") == "int &" )
  {
    if( !PyDict_Check(resultobj) )
      resultobj = PyDict_New();
    PyDict_SetItem( resultobj, PyLong_FromLong(PyDict_Size(resultobj)), PyLong_FromLong(*$1) );
  }
}
#endif

%typemap(in) FIX::DataDictionary const *& (FIX::DataDictionary* temp) {
  $1 = new FIX::DataDictionary*[1];
  *$1 = temp;
}

%typemap(free) FIX::DataDictionary const *& {
  delete[] temp;
}

%typemap(argout) FIX::DataDictionary const *& {
  void* argp;
  FIX::DataDictionary* pDD = 0;
  int res = SWIG_ConvertPtr($input, &argp, SWIGTYPE_p_FIX__DataDictionary, 0 );
  pDD = reinterpret_cast< FIX::DataDictionary * >(argp);
  *pDD = *(*$1);
}

%pythoncode %{
#ifdef SWIGPYTHON
try:
  import thread
except ImportError:
  import _thread as thread

def _quickfix_start_thread(i_or_a):
  i_or_a.block()
#endif
%}

%feature("shadow") FIX::Initiator::start() %{
def start(self):
  thread.start_new_thread(_quickfix_start_thread, (self,))
%}

%feature("shadow") FIX::Acceptor::start() %{
def start(self):
  thread.start_new_thread(_quickfix_start_thread, (self,))
%}

%feature("director:except") FIX::Application::onCreate {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    PyErr_Restore( ptype, pvalue, ptraceback );
    PyErr_Print();
    Py_Exit(1);
  }
#endif
}

%feature("director:except") FIX::Application::onLogon {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    PyErr_Restore( ptype, pvalue, ptraceback );
    PyErr_Print();
    Py_Exit(1);
  }
#endif
}

%feature("director:except") FIX::Application::onLogout {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    PyErr_Restore( ptype, pvalue, ptraceback );
    PyErr_Print();
    Py_Exit(1);
  }
#endif
}

%feature("director:except") FIX::Application::toAdmin {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    PyErr_Restore( ptype, pvalue, ptraceback );
    PyErr_Print();
    Py_Exit(1);
  }
#endif
}

%feature("director:except") FIX::Application::toApp {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    void *result;

    try {
      if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__DoNotSend, 0 ) != -1 ) {
  throw *((FIX::DoNotSend*)result);
      } else {
        PyErr_Restore( ptype, pvalue, ptraceback );
        PyErr_Print();
        Py_Exit(1);
      }
    } catch( std::exception& e ) {
      std::cout << e.what() << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    } catch( ... ) {
      std::cout << "Fatal exception" << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    }
  }
#endif
}

%feature("director:except") FIX::Application::fromAdmin {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    void *result;

    try {
      if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__FieldNotFound, 0 ) != -1 ) {
  throw *((FIX::FieldNotFound*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__IncorrectDataFormat, 0 ) != -1 ) {
        throw *((FIX::IncorrectDataFormat*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__IncorrectTagValue, 0 ) != -1 ) {
        throw *((FIX::IncorrectTagValue*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__RejectLogon, 0 ) != -1 ) {
        throw *((FIX::RejectLogon*)result);
      } else {
        PyErr_Restore( ptype, pvalue, ptraceback );
        PyErr_Print();
        Py_Exit(1);
      }
    } catch( std::exception& e ) {
      std::cout << e.what() << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    } catch( ... ) {
      std::cout << "Fatal exception" << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    }
  }
#endif
}

%feature("director:except") FIX::Application::fromApp {
#ifdef SWIGPYTHON
  if( $error != NULL ) {
    PyObject *ptype, *pvalue, *ptraceback;
    PyErr_Fetch( &ptype, &pvalue, &ptraceback );
    void *result;

    try {
      if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__FieldNotFound, 0 ) != -1 ) {
  throw *((FIX::FieldNotFound*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__IncorrectDataFormat, 0 ) != -1 ) {
        throw *((FIX::IncorrectDataFormat*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__IncorrectTagValue, 0 ) != -1 ) {
        throw *((FIX::IncorrectTagValue*)result);
      } else if( SWIG_ConvertPtr(pvalue, &result, SWIGTYPE_p_FIX__UnsupportedMessageType, 0 ) != -1 ) {
        throw *((FIX::UnsupportedMessageType*)result);
      } else {
        PyErr_Restore( ptype, pvalue, ptraceback );
        PyErr_Print();
        Py_Exit(1);
      }
    } catch( std::exception& e ) {
      std::cout << e.what() << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    } catch( ... ) {
      std::cout << "Fatal exception" << std::endl;
      Py_XDECREF( ptype );
      Py_XDECREF( pvalue );
      Py_XDECREF( ptraceback );
      throw;
    }
  }
#endif
}

%include <Exceptions.h>
%include <Field.h>
%include <FieldMap.h>
%include <Message.h>
%include <Group.h>
%include <Fields.h>
%include <FixFields.h>
%include <Values.h>
%include <FixValues.h>
%include <SessionID.h>
%include <Dictionary.h>
%include <SessionSettings.h>
%include <Session.h>
%include <SessionID.h>
%include <Log.h>
%include <FileLog.h>
%include <MessageStore.h>
%include <FileStore.h>
%include <Application.h>
%include <Initiator.h>
%include <SocketInitiator.h>
%include <Acceptor.h>
%include <SocketAcceptor.h>
%include <DataDictionary.h>

%pythoncode %{
#ifdef SWIGPYTHON
class SocketInitiator(SocketInitiatorBase):
  application = 0
  storeFactory = 0
  setting = 0
  logFactory = 0

  def __init__(self, application, storeFactory, settings, logFactory=None):
    if logFactory == None:
      SocketInitiatorBase.__init__(self, application, storeFactory, settings)
    else:
      SocketInitiatorBase.__init__(self, application, storeFactory, settings, logFactory)

    self.application = application
    self.storeFactory = storeFactory
    self.settings = settings
    self.logFactory = logFactory

class SocketAcceptor(SocketAcceptorBase):
  application = 0
  storeFactory = 0
  setting = 0
  logFactory = 0

  def __init__(self, application, storeFactory, settings, logFactory=None):
    if logFactory == None:
      SocketAcceptorBase.__init__(self, application, storeFactory, settings)
    else:
      SocketAcceptorBase.__init__(self, application, storeFactory, settings, logFactory)

    self.application = application
    self.storeFactory = storeFactory
    self.settings = settings
    self.logFactory = logFactory
#endif
%}

%init %{
#ifndef _MSC_VER
      struct sigaction new_action, old_action;
      new_action.sa_handler = SIG_DFL;
      sigemptyset( &new_action.sa_mask );
      new_action.sa_flags = 0;
      sigaction( SIGINT, &new_action, &old_action );
#endif
%}
```

@orenmnero @quickfix At this point I'm not sure what's causing the issue, as the generated C++ code for the `getFieldName`, `getValueName` and `getGroup` look like this.
```cpp
SWIGINTERN PyObject *_wrap_DataDictionary_getFieldName(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  FIX::DataDictionary *arg1 = (FIX::DataDictionary *) 0 ;
  int arg2 ;
  std::string *arg3 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  int val2 ;
  int ecode2 = 0 ;
  void *argp3 = 0 ;
  int res3 = 0 ;
  PyObject * obj0 = 0 ;
  PyObject * obj1 = 0 ;
  PyObject * obj2 = 0 ;
  bool result;
  
  if (!PyArg_ParseTuple(args,(char *)"OOO:DataDictionary_getFieldName",&obj0,&obj1,&obj2)) SWIG_fail;
  res1 = SWIG_ConvertPtr(obj0, &argp1,SWIGTYPE_p_FIX__DataDictionary, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "DataDictionary_getFieldName" "', argument " "1"" of type '" "FIX::DataDictionary const *""'"); 
  }
  arg1 = reinterpret_cast< FIX::DataDictionary * >(argp1);
  ecode2 = SWIG_AsVal_int(obj1, &val2);
  if (!SWIG_IsOK(ecode2)) {
    SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "DataDictionary_getFieldName" "', argument " "2"" of type '" "int""'");
  } 
  arg2 = static_cast< int >(val2);
  res3 = SWIG_ConvertPtr(obj2, &argp3, SWIGTYPE_p_std__string,  0 );
  if (!SWIG_IsOK(res3)) {
    SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "DataDictionary_getFieldName" "', argument " "3"" of type '" "std::string &""'"); 
  }
  if (!argp3) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getFieldName" "', argument " "3"" of type '" "std::string &""'"); 
  }
  arg3 = reinterpret_cast< std::string * >(argp3);
  {
    SWIG_PYTHON_THREAD_BEGIN_ALLOW;
    result = (bool)((FIX::DataDictionary const *)arg1)->getFieldName(arg2,*arg3);
    SWIG_PYTHON_THREAD_END_ALLOW;
  }
  resultobj = SWIG_From_bool(static_cast< bool >(result));
  return resultobj;
fail:
  return NULL;
}

SWIGINTERN PyObject *_wrap_DataDictionary_getGroup(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  FIX::DataDictionary *arg1 = (FIX::DataDictionary *) 0 ;
  std::string *arg2 = 0 ;
  int arg3 ;
  int *arg4 = 0 ;
  FIX::DataDictionary **arg5 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  int res2 = SWIG_OLDOBJ ;
  int val3 ;
  int ecode3 = 0 ;
  void *argp4 = 0 ;
  int res4 = 0 ;
  void *argp5 = 0 ;
  int res5 = 0 ;
  PyObject * obj0 = 0 ;
  PyObject * obj1 = 0 ;
  PyObject * obj2 = 0 ;
  PyObject * obj3 = 0 ;
  PyObject * obj4 = 0 ;
  bool result;
  
  if (!PyArg_ParseTuple(args,(char *)"OOOOO:DataDictionary_getGroup",&obj0,&obj1,&obj2,&obj3,&obj4)) SWIG_fail;
  res1 = SWIG_ConvertPtr(obj0, &argp1,SWIGTYPE_p_FIX__DataDictionary, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "DataDictionary_getGroup" "', argument " "1"" of type '" "FIX::DataDictionary const *""'"); 
  }
  arg1 = reinterpret_cast< FIX::DataDictionary * >(argp1);
  {
    std::string *ptr = (std::string *)0;
    res2 = SWIG_AsPtr_std_string(obj1, &ptr);
    if (!SWIG_IsOK(res2)) {
      SWIG_exception_fail(SWIG_ArgError(res2), "in method '" "DataDictionary_getGroup" "', argument " "2"" of type '" "std::string const &""'"); 
    }
    if (!ptr) {
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getGroup" "', argument " "2"" of type '" "std::string const &""'"); 
    }
    arg2 = ptr;
  }
  ecode3 = SWIG_AsVal_int(obj2, &val3);
  if (!SWIG_IsOK(ecode3)) {
    SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "DataDictionary_getGroup" "', argument " "3"" of type '" "int""'");
  } 
  arg3 = static_cast< int >(val3);
  res4 = SWIG_ConvertPtr(obj3, &argp4, SWIGTYPE_p_int,  0 );
  if (!SWIG_IsOK(res4)) {
    SWIG_exception_fail(SWIG_ArgError(res4), "in method '" "DataDictionary_getGroup" "', argument " "4"" of type '" "int &""'"); 
  }
  if (!argp4) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getGroup" "', argument " "4"" of type '" "int &""'"); 
  }
  arg4 = reinterpret_cast< int * >(argp4);
  res5 = SWIG_ConvertPtr(obj4, &argp5, SWIGTYPE_p_p_FIX__DataDictionary,  0 );
  if (!SWIG_IsOK(res5)) {
    SWIG_exception_fail(SWIG_ArgError(res5), "in method '" "DataDictionary_getGroup" "', argument " "5"" of type '" "FIX::DataDictionary const *&""'"); 
  }
  if (!argp5) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getGroup" "', argument " "5"" of type '" "FIX::DataDictionary const *&""'"); 
  }
  arg5 = reinterpret_cast< FIX::DataDictionary ** >(argp5);
  {
    SWIG_PYTHON_THREAD_BEGIN_ALLOW;
    result = (bool)((FIX::DataDictionary const *)arg1)->getGroup((std::string const &)*arg2,arg3,*arg4,(FIX::DataDictionary const *&)*arg5);
    SWIG_PYTHON_THREAD_END_ALLOW;
  }
  resultobj = SWIG_From_bool(static_cast< bool >(result));
  if (SWIG_IsNewObj(res2)) delete arg2;
  return resultobj;
fail:
  if (SWIG_IsNewObj(res2)) delete arg2;
  return NULL;
}

SWIGINTERN PyObject *_wrap_DataDictionary_getValueName(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  FIX::DataDictionary *arg1 = (FIX::DataDictionary *) 0 ;
  int arg2 ;
  std::string *arg3 = 0 ;
  std::string *arg4 = 0 ;
  void *argp1 = 0 ;
  int res1 = 0 ;
  int val2 ;
  int ecode2 = 0 ;
  int res3 = SWIG_OLDOBJ ;
  void *argp4 = 0 ;
  int res4 = 0 ;
  PyObject * obj0 = 0 ;
  PyObject * obj1 = 0 ;
  PyObject * obj2 = 0 ;
  PyObject * obj3 = 0 ;
  bool result;
  
  if (!PyArg_ParseTuple(args,(char *)"OOOO:DataDictionary_getValueName",&obj0,&obj1,&obj2,&obj3)) SWIG_fail;
  res1 = SWIG_ConvertPtr(obj0, &argp1,SWIGTYPE_p_FIX__DataDictionary, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "DataDictionary_getValueName" "', argument " "1"" of type '" "FIX::DataDictionary const *""'"); 
  }
  arg1 = reinterpret_cast< FIX::DataDictionary * >(argp1);
  ecode2 = SWIG_AsVal_int(obj1, &val2);
  if (!SWIG_IsOK(ecode2)) {
    SWIG_exception_fail(SWIG_ArgError(ecode2), "in method '" "DataDictionary_getValueName" "', argument " "2"" of type '" "int""'");
  } 
  arg2 = static_cast< int >(val2);
  {
    std::string *ptr = (std::string *)0;
    res3 = SWIG_AsPtr_std_string(obj2, &ptr);
    if (!SWIG_IsOK(res3)) {
      SWIG_exception_fail(SWIG_ArgError(res3), "in method '" "DataDictionary_getValueName" "', argument " "3"" of type '" "std::string const &""'"); 
    }
    if (!ptr) {
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getValueName" "', argument " "3"" of type '" "std::string const &""'"); 
    }
    arg3 = ptr;
  }
  res4 = SWIG_ConvertPtr(obj3, &argp4, SWIGTYPE_p_std__string,  0 );
  if (!SWIG_IsOK(res4)) {
    SWIG_exception_fail(SWIG_ArgError(res4), "in method '" "DataDictionary_getValueName" "', argument " "4"" of type '" "std::string &""'"); 
  }
  if (!argp4) {
    SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "DataDictionary_getValueName" "', argument " "4"" of type '" "std::string &""'"); 
  }
  arg4 = reinterpret_cast< std::string * >(argp4);
  {
    SWIG_PYTHON_THREAD_BEGIN_ALLOW;
    result = (bool)((FIX::DataDictionary const *)arg1)->getValueName(arg2,(std::string const &)*arg3,*arg4);
    SWIG_PYTHON_THREAD_END_ALLOW;
  }
  resultobj = SWIG_From_bool(static_cast< bool >(result));
  if (SWIG_IsNewObj(res3)) delete arg3;
  return resultobj;
fail:
  if (SWIG_IsNewObj(res3)) delete arg3;
  return NULL;
}
```

Obviously the pull request will need some cleaning and a squash of the commit history when it gets fixed up but I could really use some guidance here with what could be the cause of the issues.

**Comment by wldcordeiro** [comment]
My fork will now build and run on Python 3. There is an issue with the build not working on Python 2 (the annotations in Python 3 cause a syntax error) if anyone wants to try out Python 3 support you can clone my [repo.](https://github.com/wldcordeiro/quickfix)

**Comment by wamatt** [comment]
any plans to officially support quickfix on python 3?

**Comment by MaximilianR** [comment]
@wldcordeiro Has your branch moved? The link doesn't work.

Any desire from the maintainers to integrate it into the main repo?

**Comment by andradei** [comment]
@MaximilianR The fork has been discontinued.
